In [5]:
import statsmodels.api as st
iris = st.datasets.get_rdataset('iris','datasets')
y = iris.data.Species
x = iris.data.ix[:, 0:4]
x = st.add_constant(x, prepend = False)

/Users/dlai/venv/JupyterNotebook/lib/python3.7/site-packages/statsmodels/datasets/utils.py:192: FutureWarning: `item` has been deprecated and will be removed in a future version
  return dataset_meta["Title"].item()
/Users/dlai/venv/JupyterNotebook/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.
/Users/dlai/venv/JupyterNotebook/lib/python3.7/site-packages/pandas/core/indexing.py:822: FutureWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
/Users/dlai/venv/JupyterNotebook/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2495: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)

In [ ]:
y.unique()

In [4]:
iris.data

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [6]:
mdl = st.MNLogit(y, x)
mdl_fit = mdl.fit(method='bfgs')
print (mdl_fit.summary())

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.057112
         Iterations: 35
         Function evaluations: 37
         Gradient evaluations: 37
                          MNLogit Regression Results
==============================================================================
Dep. Variable:                Species   No. Observations:                  150
Model:                        MNLogit   Df Residuals:                      140
Method:                           MLE   Df Model:                            8
Date:                Wed, 30 Oct 2019   Pseudo R-squ.:                  0.9480
Time:                        19:23:53   Log-Likelihood:                -8.5668
converged:                      False   LL-Null:                       -164.79
Covariance Type:            nonrobust   LLR p-value:                 9.200e-63
=====================================================================================
Species=versicolor       coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
Sepal.Length          -1.4959    444.817     -0.003      0.997    -873.321     870.330
Sepal.Width           -8.0560    282.766     -0.028      0.977    -562.267     546.155
Petal.Length          11.9301    374.116      0.032      0.975    -721.323     745.184
Petal.Width            1.7039    759.366      0.002      0.998   -1486.627    1490.035
const                  1.6444   1550.515      0.001      0.999   -3037.309    3040.597
--------------------------------------------------------------------------------------
Species=virginica       coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
Sepal.Length         -8.0348    444.835     -0.018      0.986    -879.896     863.827
Sepal.Width         -15.8195    282.793     -0.056      0.955    -570.083     538.444
Petal.Length         22.1797    374.155      0.059      0.953    -711.151     755.511
Petal.Width          14.0603    759.384      0.019      0.985   -1474.304    1502.425
const                -6.5053   1550.533     -0.004      0.997   -3045.494    3032.483
=====================================================================================

/Users/dlai/venv/JupyterNotebook/lib/python3.7/site-packages/statsmodels/base/model.py:512: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)

In [7]:
mdl_fit.predict(x)

                0             1             2
0    1.000000e+00  3.606891e-08  1.094370e-30
1    9.999973e-01  2.731546e-06  1.486685e-26
2    9.999998e-01  2.230922e-07  3.410330e-28
3    9.999937e-01  6.303118e-06  3.128062e-25
4    1.000000e+00  1.871674e-08  5.024329e-31
..            ...           ...           ...
145  4.800939e-18  1.551948e-03  9.984481e-01
146  1.655677e-18  2.543885e-03  9.974561e-01
147  6.436227e-17  1.683120e-02  9.831688e-01
148  5.738820e-19  1.698114e-04  9.998302e-01
149  7.980238e-17  1.104528e-02  9.889547e-01

[150 rows x 3 columns]